- project:
    name: openstack-dev/sandbox
    check:
      jobs:
        - tox-pep8
    post:
      jobs:
        - publish-openstack-python-branch-tarball
    release:
      jobs:
        - release-openstack-python
