- project:
    name: openstack-dev/sandbox
    check:
      jobs:
        - tox-docs
    gate:
      jobs:
        - tox-docs
    post:
      jobs:
        - publish-openstack-python-docs:
            vars:
              afs_publisher_target: 'sandbox'
        - publish-openstack-python-branch-tarball
